# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  BytestreamLib_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := BytestreamLib

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

BytestreamLib:
ifneq (,$(BytestreamLib_config))
	@echo "==== Building BytestreamLib ($(BytestreamLib_config)) ===="
	@${MAKE} --no-print-directory -C . -f BytestreamLib.make config=$(BytestreamLib_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f BytestreamLib.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   BytestreamLib"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"